chore: package-lock update
apache/cordova-lib pull request #879
Opened 2021-09-11 18:57 UTC by breautek

### Platforms affected

### Motivation and Context

Resolves ~9 sub-dependency vulnerabilities

### Description

### Testing

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

2021-09-11 21:14 UTC, NiklasMerz approved these changes
Audit issues are really annoying. Tests pass and 0 audit issues in lib now.

Thank :+1: 

**Edit: This test was flawed as I thought my NPM credentials changed**

2021-09-11 21:22 UTC, NiklasMerz requested changes
I just checked package.json again and found out all URLs point to a totalpave registry: `https://registry.totalpave.com`

@breautek Please rebuild package-lock.json again with the NPM registry setup. 

Do we want to upgrade to the new lockfile version as well? My NPM started to print these warnings but I don't know the changes and consequences yet.

2021-09-11 21:28 UTC, dpogue commented
> Do we want to upgrade to the new lockfile version as well? My NPM started to print these warnings but I don't know the changes and consequences yet.

Will the older npm versions on older node versions on GHA properly handle the updated lockfile format?

2021-09-11 21:33 UTC, breautek commented
> I just checked package.json again and found out all URLs point to a totalpave registry: `https://registry.totalpave.com`
> 
> @breautek Please rebuild package-lock.json again with the NPM registry setup.
> 
> Do we want to upgrade to the new lockfile version as well? My NPM started to print these warnings but I don't know the changes and consequences yet.

Argh! Oops!

That's work stuff bleeding in... ill fix it when i get home

2021-09-11 21:34 UTC, breautek commented
> > Do we want to upgrade to the new lockfile version as well? My NPM started to print these warnings but I don't know the changes and consequences yet.
> 
> Will the older npm versions on older node versions on GHA properly handle the updated lockfile format?

Npm will still work with a message that "it will try its best".

But not really sure what that means exactly.

2021-09-11 21:43 UTC, breautek commented
@NiklasMerz do you think there would be pushback if we start adding .npmrc configs to our cordova repos to re-assert npm registry is npms official registry?

Would avoid mistakes like this in the future by having a project level npm config.

2021-09-12 01:07 UTC, breautek commented
Set my registry back to `registry.npmjs.org` and regenerated the package-lock. This PR is rebased for the correction.

2021-09-12 04:39 UTC, erisu approved these changes

2021-09-12 09:42 UTC, NiklasMerz approved these changes

2021-09-12 09:59 UTC, merged

2021-09-12 14:40 UTC, purplecabbage commented
Mostly we should not be committing package-lock, except for the cli itself ... am I missing something?

2021-09-12 15:09 UTC, breautek commented
Package-lock is intended to be committed, as it ensures that two developers on two different machines will install the exact same dependencies when they run npm install.

Not to be confused when users are using this package as a library, in which case their root package-lock is used.

From NPM: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

This file is intended to be committed into source repositories, and serves various purposes:

Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

Facilitate greater visibility of tree changes through readable source control diffs.

Optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

As of npm v7, lockfiles include enough information to gain a complete picture of the package tree, reducing the need to read package.json files, and allowing for significant performance improvements.

2021-09-12 16:11 UTC, purplecabbage commented
This sums up what I think ...
Apps yes, libs no

https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

2021-09-12 17:11 UTC, breautek commented
There was a consensus back in 2018 via https://github.com/apache/cordova/issues/4#issuecomment-420728477 to add package-locks, which is why variety of our packages have package-locks.

If you ask my personal opinion on package-locks, I hate them, mostly for the reasons described by sindresorhus.

However, not committing them still presents the same issues described by sindresorhus, unless we (the maintainers) are constantly wiping the package-lock & node_modules and reinstalling from scratch. We could configure NPM via `.npmrc` to disable package locks so they won't be generated in the first place but this also have a few consequences:

1. node_modules are not automatically pruned if package-locks are disabled. They can be manually pruned via `npm prune`.
2. NPM installs will be slower (however not sure how significant since most cordova repos are fairly small anyway)
3. npm ci command requires package-lock or shrinkwrap, so CI workflows may have to be updated accordingly to use `npm install` instead.
4. npm audit I believe also requires package-lock or shrinkwrap

Despite it's flaws I think the benefits of package-lock still outweighs the consequences of not committing/disabling package-lock.

2021-09-12 17:17 UTC, purplecabbage commented
Okay, yeah that makes sense. 
Let's commit 'em